// import "./assets/styles/autogenerated.css";
import "./assets/styles/index.scss";
import Button from "./components/Button";
import Popover from "./components/Popover";
import Radio from "./components/Radio";
import Modal from "./components/Modal";
import Drawer from "./components/Drawer";
import Input from "./components/Input";
import Table from "./components/Table";
import Tabs from "./components/Tabs";
import Pagination from "./components/Pagination";
import Spinner from "./components/Spinner";
import Select from "./components/Select";
import ModalEnhanced from "./components/ModalEnhanced";
import SlideDownUp from "./components/SlideDownUp";
import Tooltip from "./components/Tooltip";
import DatePicker from "./components/DatePicker";

export {
  Button,
  Radio,
  Popover,
  Modal,
  Drawer,
  Input,
  Table,
  Tabs,
  Pagination,
  Spinner,
  Select,
  ModalEnhanced,
  SlideDownUp,
  Tooltip,
  DatePicker,
};

/*Types*/
import { PopoverReport, PopoverProps, PopoverTriggerEvents } from "./components/Popover";
import { ModalRefs, ModalProps } from "./components/Modal";
import { InputProps } from "./components/Input";
import { ButtonProps, ButtonSize } from "./components/Button";
import { RadioGroupProps, RadioButtonExtensionProps, RadioButtonProps } from "./components/Radio";
import { DrawerRefs, DrawerProps } from "./components/Drawer";
import { TableProps, Column, Order, SortEvent } from "./components/Table";
import { Tab, TabsProps } from "./components/Tabs";
import { PaginationProps } from "./components/Pagination";
import { SpinnerProps } from "./components/Spinner";
import { Placeholder } from "./types";
import { OptionProps } from "./components/Select";
import { ModalEnhancedProps, ModalEnhancedRefs } from "./components/ModalEnhanced";
import { DatePickEvent, DatePickerProps } from "./components/DatePicker";

export type {
  PopoverReport,
  ModalRefs,
  ModalProps,
  InputProps,
  ButtonProps,
  ButtonSize,
  PopoverProps,
  PopoverTriggerEvents,
  RadioGroupProps,
  RadioButtonExtensionProps,
  RadioButtonProps,
  DrawerRefs,
  DrawerProps,
  TableProps,
  Column,
  Order,
  SortEvent,
  Tab,
  TabsProps,
  PaginationProps,
  SpinnerProps,
  Placeholder,
  OptionProps,
  ModalEnhancedProps,
  ModalEnhancedRefs,
  DatePickEvent,
  DatePickerProps,
};
