name: Deploy production

on:
  release:
    types:
      - released

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: darwinia-network/devops
          path: .github

      - name: Install dependencies
        run: |
          yarn install
          yarn boot

      - name: Build
        run: yarn build:app

      - uses: ./.github/actions/smart-vercel
        name: Deploy to Vercel
        id: smart-vercel
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          project_name: feemarket
          dist_path: packages/app/dist
          prod_mode: true
          script_run: false
          enable_cache: true
          enable_notify_slack: true
          slack_channel: darwinia-apps
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
